version: "3.9"

services:
  neo4j_db2:
    image: neo4j:5
    container_name: neo4j_db3
    environment:
      - NEO4J_AUTH=neo4j/superpass123
    ports:
      - "7476:7474"   # HTTP (Neo4j Browser)
      - "7689:7687"   # Bolt (conexión desde API/driver)
    networks:
      - mynet

  api_service:
    build:
      context: ./api        # Ruta donde está el Dockerfile de tu API
      dockerfile: Dockerfile
    container_name: api_service2
    environment:
      - NEO4J_URI=bolt://neo4j_db2:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=superpass123
      - EXPRESS_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - neo4j_db2
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

